### ISSUE TITLE
convertSwagger2markup fails with NPE with swagger files with schema json objects

### ISSUE THREAD

**Issue by fooinha** [Swagger2Markup/swagger2markup-maven-plugin#31]
convertSwagger2markup fails with NPE.

This happens because if input swagger file has json objects schema  like this one

```json
      "schema" : {
          "$ref" : "#/definitions/APIResult"
      }
```

When removing all **schema** json nodes from input swagger file, the generation finishes without error.

pom.xml

```xml

        <swagger2markup.version>1.2.0</swagger2markup.version>

```

Stacktrace

```java

Failed to execute goal 'convertSwagger2markup'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to execute goal 'convertSwagger2markup'
	at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at io.github.swagger2markup.internal.adapter.PropertyAdapter.getType(PropertyAdapter.java:116)
	at io.github.swagger2markup.internal.adapter.PropertyAdapter.getType(PropertyAdapter.java:123)
	at io.github.swagger2markup.internal.component.ResponseComponent.lambda$apply$1(ResponseComponent.java:106)
	at java.util.TreeMap.forEach(TreeMap.java:1001)
	at io.github.swagger2markup.internal.component.ResponseComponent.apply(ResponseComponent.java:82)
	at io.github.swagger2markup.internal.component.PathOperationComponent.buildResponsesSection(PathOperationComponent.java:227)
	at io.github.swagger2markup.internal.component.PathOperationComponent.apply(PathOperationComponent.java:106)
	at io.github.swagger2markup.internal.document.PathsDocument.applyPathOperationComponent(PathsDocument.java:223)
	at io.github.swagger2markup.internal.document.PathsDocument.buildOperation(PathsDocument.java:207)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$null$1(PathsDocument.java:133)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.swagger2markup.internal.document.PathsDocument.lambda$buildsPathsSection$2(PathsDocument.java:133)
	at java.util.TreeMap.forEach(TreeMap.java:1001)
	at io.github.swagger2markup.internal.document.PathsDocument.buildsPathsSection(PathsDocument.java:127)
	at io.github.swagger2markup.internal.document.PathsDocument.apply(PathsDocument.java:103)
	at io.github.swagger2markup.Swagger2MarkupConverter.applyPathsDocument(Swagger2MarkupConverter.java:197)
	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:182)
	at io.github.swagger2markup.Swagger2MarkupMojo.execute(Swagger2MarkupMojo.java:69)
	... 22 more
```

**Comment by fooinha** [comment]
Maybe a duplicate of https://github.com/Swagger2Markup/swagger2markup/issues/213

**Comment by RobWin** [comment]
Hi, could you please provide a minimal Swagger Spec to reproduce this issue?

**Comment by fooinha** [comment]
Hi, here you go. Thanx.


```json

{
  "swagger" : "2.0",
  "info" : {
    "description" : "description",
    "version" : "v1",
    "title" : "title",
    "contact" : {
      "name" : "contact",
      "url" : "foo.tld",
      "email" : "noone@foo.tld"
    }
  },
  "host" : "localhost:8000",
  "basePath" : "/",
  "tags" : [ {
    "name" : "stuff",
    "description" : "workers Operations"
  }, {
    "name" : "things",
    "description" : "things Operations"
  }, {
    "name" : "choices",
    "description" : "choices Operations"
  } ],
  "schemes" : [ "http", "https" ],
  "paths" : {
    "/stuff" : {
      "post" : {
        "tags" : [ "stuff" ],
        "summary" : "Creates a new workers entry and returning it's ID",
        "description" : "",
        "operationId" : "createworkers",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "workers",
          "description" : "workers Data for creation",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/workersData"
          }
        } ],
        "responses" : {
          "303" : {
            "description" : "Redirects to created workers URL"
          },
          "400" : {
            "description" : "Invalid data"
          },
          "500" : {
            "description" : "If an internal error happens"
          }
        }
      }
    }
  }
}


```

**Comment by RobWin** [comment]
The Definition section is missing. Is this by mistake?

**Comment by fooinha** [comment]
Yes. sorry. I made that mistake by creating the minimal version. I'll try to do it again. Thanx.

**Comment by RobWin** [comment]
You can edit the existing comment.

**Comment by fooinha** [comment]
Debugging it further, i see that this happens while processing response headers


https://github.com/Swagger2Markup/swagger2markup/blob/v1.2.0/src/main/java/io/github/swagger2markup/internal/adapter/PropertyAdapter.java#L123

definitionDocumentResolver == null ?
